#!/bin/bash

# project 3
# open-vocab

eng_filename=$1
frn_filename=$2
stdout_file=$3

#
#   We will be running this script to grade your assignment. Note that failure
# to run this program with this script will result in a 15% deduction in your
# grade, regardless of if you provide other instructions on how to run your
# program.
#
#   If you are having difficulty getting the script to run your program, talk
# to the TAs.
##############################################################################

python main.py --num_rnn_layers=1 --bidirectional=True --batch_size=32 --epochs=1 --embedding_size=256 --hidden_size=512 --lr=1e-3 --version="bpe" --french_file="data/multi-combined-input-lines.txt" --english_file="data/multi-combined-output-lines.txt" 
python main.py --num_rnn_layers=1 --bidirectional=True --batch_size=32 --epochs=1 --embedding_size=256 --hidden_size=512 --lr=1e-3 --version="bpe" --french_file="data/multi-f2e-input-lines.txt" --english_file="data/multi-f2e-output-lines.txt" 
python main.py --num_rnn_layers=1 --bidirectional=True --batch_size=32 --epochs=1 --embedding_size=256 --hidden_size=512 --lr=1e-3 --version="bpe" --french_file="data/multi-g2e-input-lines.txt" --english_file="data/multi-g2e-output-lines.txt" 

##############################################################################
# Run this script with the command
#
#   ./seq2seq eng_bpe.txt frn_bpe.txt out.txt



